In [1]:
import pandas as pd

In [3]:
s1 = "abcd"
s2 = "bcfe"

m, n = len(s1), len(s2)

# dp[i][j] -> min edits to convert s1[0..i] to s2[0..j]
dp = [[0 for _ in range(n + 1)] for _ in range(m + 1)]

print(f"s1 = {s1}, length m = {m}")
print(f"s2 = {s2}, length n = {n}")
print(f"Table size: {m+1} x {n+1}")

s1 = abcd, length m = 4
s2 = bcfe, length n = 4
Table size: 5 x 5

In [5]:
for i in range(m + 1):
    dp[i][0] = i

for j in range(n + 1):
    dp[0][j] = j

# Display table so far
pd.DataFrame(dp, index=["∅"] + list(s1), columns=["∅"] + list(s2))

   ∅  b  c  f  e
∅  0  1  2  3  4
a  1  0  0  0  0
b  2  0  0  0  0
c  3  0  0  0  0
d  4  0  0  0  0

In [7]:
for i in range(1, m + 1):
    for j in range(1, n + 1):
        if s1[i - 1] == s2[j - 1]:
            dp[i][j] = dp[i - 1][j - 1]
        else:
            dp[i][j] = 1 + min(
                dp[i][j - 1],      # Insert
                dp[i - 1][j],      # Remove
                dp[i - 1][j - 1]   # Replace
            )

# Display the fully filled table
pd.DataFrame(dp, index=["∅"] + list(s1), columns=["∅"] + list(s2))

   ∅  b  c  f  e
∅  0  1  2  3  4
a  1  1  2  3  4
b  2  1  2  3  4
c  3  2  1  2  3
d  4  3  2  2  3

In [9]:
print(f"Minimum Edit Distance between '{s1}' and '{s2}' is: {dp[m][n]}")

Minimum Edit Distance between 'abcd' and 'bcfe' is: 3